# docker-compose build
version: '3.9'
services:
  db:
    image: kartoza/postgis:16-3.4
    container_name: carshare360-db
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=${POSTGRE_DATABASE}
      - POSTGRES_USER=${POSTGRE_USERNAME}
      - POSTGRES_PASS=${POSTGRE_PASSWORD}
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=true
    ports:
      - "${POSTGRE_PORT}:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d gis"
  app:
    build: .
    container_name: carshare360-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - POSTGRE_HOST=db
      - POSTGRE_PORT=${POSTGRE_PORT}
      - POSTGRE_DATABASE=${POSTGRE_DATABASE}
      - POSTGRE_USERNAME=${POSTGRE_USERNAME}
      - POSTGRE_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRE_SYNCHRONIZE=${POSTGRE_SYNCHRONIZE}
      - POSTGRE_LOGGING=${POSTGRE_LOGGING}
      - AUTH_SECRET=${AUTH_SECRET}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    restart: on-failure